[package]
name = "deities"
description = "Deities is a magic around system services supervisor, launcher and auto configurator"
version = "0.2.0"
authors = ["Daniel (dmilith) Dettlaff <dmilith@me.com>"]

[dependencies]
toml = "0.2"
glob = "0.2"
rustc-serialize = "0.3"
log = "0.3"
colored = "1.4"
fern = "0.3"
time = "0.1"
libc = "0.2"
